### ISSUE TITLE
Feb 2020 Is detected?

### ISSUE THREAD

**Issue by TauCSGO** [danielkrupinski/curiuminjector-csgo#3]
Feb 2020 Is detected?

**Comment by itchy2019** [comment]
...

**Comment by gaston010** [comment]
Lo uso hace 7 mese y no lo detecta , Lo tengo al .dll y este con vmp

**Comment by CSGOCheatsArg** [comment]
> Lo uso hace 7 mese y no lo detecta , Lo tengo al .dll y este con vmp

Si si, lo estoy usando con el vmp a ambos y va bien
Gracias por responder

**Comment by TauCSGO** [comment]
> Lo uso hace 7 mese y no lo detecta , Lo tengo al .dll y este con vmp

Se habra detectado en esta nueva VAC WAVE?
