### ISSUE TITLE
JUNE 2020 DETECTED

### ISSUE THREAD

**Issue by TauCSGO** [danielkrupinski/curiuminjector-csgo#7]
Confirmed: DETECTED

**Comment by kussamun55** [comment]
It's working just run as ur program.

**Comment by S3NP41** [comment]
did you change like the code or just build the original

**Comment by TauCSGO** [comment]
> did you change like the code or just build the original

I change the code every week
But what was detected was Osiris ( https://github.com/danielkrupinski/Osiris) , between 28 / MAY and 02 / JUN
I close the case
Thanks
